default: &default
  adapter: postgresql
  schema_search_path: "public,shared_extensions"
  username: postgres
  password: welcome

  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: list_system
  host: localhost
  port: 5432

development:
  <<: *default
  database: list_system_test
  host: localhost
  port: 5432
